Payments/Payments/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Payments.Data;
using Payments.Models;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Net.Sockets;
using System.Xml.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;
using ExcelDataReader;
using System.Text;
using Microsoft.EntityFrameworkCore.Sqlite;
using System.Linq;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using System.Security.Cryptography;
using Org.BouncyCastle.Crypto.Generators;
using BCrypt;

namespace Payments.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        [HttpGet]
        public IActionResult Index()
        {


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(string email, string password)
        {
            // Проверяем, что оба поля заполнены
            if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
            {
                // Если какое-то поле не заполнено, возвращаем сообщение об ошибке
                ModelState.AddModelError(string.Empty, "Пожалуйста, заполните все поля.");
                return View();
            }

            var user = _context.Users.FirstOrDefault(x => x.Email == email);
            if (user != null)
            {
                if (BCrypt.Net.BCrypt.Verify(password, user.Password))
                {
                    var claims = new List<Claim> {
                        new Claim("Id", user.Id.ToString()),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Name, user.Name),
                    };

                    ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                    return RedirectToAction("Index", "Home");
                }
            }

            // Если пользователь не найден или пароль неверен, добавляем сообщение об ошибке
            ModelState.AddModelError(string.Empty, "Неверный логин или пароль.");
            return View();
        }

        [HttpGet]
        public IActionResult CreateDefaultUser()
        {
            var user = new User
            {
                Email = "m",
                Password = BCrypt.Net.BCrypt.HashPassword("1")
            };
            _context.Users.Add(user);
            _context.SaveChanges();

            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }
        
    }
}

Payments/Payments/Controllers/RevenueAndPaymentController.cs
using Library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Payments.Data;
using Payments.Models;
using System.Diagnostics;
using System.Globalization;

namespace Payments.Controllers
{
    public class RevenueAndPaymentController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly ILogger<RevenueAndPaymentController> _logger;

        public RevenueAndPaymentController(ILogger<RevenueAndPaymentController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }
        [HttpGet]
        public IActionResult PlanRevenueInput(int? VarId)
        {
            var viewModel = new HomePlanViewModel();

            if (VarId != null)
            {
                viewModel.Revenue = _context.PlanRevenues
                    .FirstOrDefault(x => x.Id == VarId);
            }
            viewModel.Revenues = _context.PlanRevenues.ToList();
            viewModel.Branches = _context.Branches.ToList(); // Получение списка филиалов
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PlanRevenueInputResult(Input input)
        {
            if (!ModelState.IsValid)
            {
                // Обработка неверных данных
                return View("Error");
            }
            // Сохранение варианта исходных данных
            if (!int.IsNegative(input.NumberBranch))
            {
                var existingPlan = _context.PlanRevenues.FirstOrDefault(x =>
                    x.Month == input.Month &&
                    x.Year == input.Year);

                if (existingPlan != null)
                {
                    // Если запись существует, обновляем данные
                    existingPlan.Name = input.Name;
                    existingPlan.Revenue = input.Revenue; // Обновляем выручку

                    _context.PlanRevenues.Update(existingPlan);
                }
                else
                {
                    // Если запись не существует, добавляем новую запись
                    var newPlan = new PlanRevenue
                    {
                        NumberBranch = input.NumberBranch,
                        Name = input.Name,
                        Month = input.Month,
                        Year = input.Year,
                        Revenue = input.Revenue,
                    };

                    _context.PlanRevenues.Add(newPlan);
                }

                _context.SaveChanges();
                // Вызываем метод автоматического обновления данных
                UpdateCalculatedRevenue(input.NumberBranch,input.Month, input.Year, input.Revenue);
                UpdateProceeds();
                UpdatePaying();
                
                UpdatePaymentForecast();
            }

            return RedirectToAction("PlanRevenueInput");
        }



        public IActionResult RemovePlanRevenue(int? VarId)
        {
            var variant = _context.PlanRevenues
                .FirstOrDefault(x => x.Id == VarId);
            if (variant != null)
            {
                _context.PlanRevenues.Remove(variant);
                _context.SaveChanges();

                TempData["message"] = $"Вариант {variant.NumberBranch} удален.";
                // Вызываем метод автоматического обновления данных
                UpdateCalculatedRevenue(variant.NumberBranch, variant.Month, variant.Year, variant.Revenue);
                UpdateProceeds();
                UpdatePaying();
                
                UpdatePaymentForecast();
            }
            else
            {
                TempData["message"] = $"Вариант не найден.";
            }
            return RedirectToAction(nameof(PlanRevenueInput));
        }
        [HttpGet]
        public IActionResult PaymentConditionInput(int? VarId)
        {
            var viewModel = new HomePlanViewModel();

            if (VarId != null)
            {
                viewModel.Condition = _context.PaymentConditions

                    .FirstOrDefault(x => x.Id == VarId);
            }
            viewModel.PaymentConditions = _context.PaymentConditions

                .ToList();
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult PaymentConditionInputResult(Input input)
        {
            if (!ModelState.IsValid)
            {
                // Обработка неверных данных
                return View("Error");
            }

            //Сохранение варианта исходных данных
            if (!int.IsNegative(input.NumberBranch))
            {
                var existVar = _context.PaymentConditions.FirstOrDefault(x =>
                                x.NumberBranch == input.NumberBranch &&
                                x.Name == input.Name &&
                                x.PayCondition == input.PayCondition);
                if (existVar != null)
                {
                    // Если запись существует, обновляем данные
                    existVar.Share = input.Share;//Обновляем сумму

                    _context.PaymentConditions.Update(existVar);
                    _context.SaveChanges();
                }
                else
                {
                    var plan = new PaymentCondition
                    {
                        NumberBranch = input.NumberBranch,
                        Name = input.Name,
                        PayCondition = input.PayCondition,
                        Share = input.Share,
                    };
                    _context.PaymentConditions.Add(plan);
                    _context.SaveChanges();
                }
               
                // Вызываем метод автоматического обновления данных
                UpdateCalculatedRevenue(input.NumberBranch, input.Month, input.Year, input.Revenue);
                UpdateProceeds();
                UpdatePaying();
                
                UpdatePaymentForecast();
            }
            
            return RedirectToAction("PaymentConditionInput");

        }
        public IActionResult RemovePaymentCondition(int? VarId)
        {
            var variant = _context.PaymentConditions
                .FirstOrDefault(x => x.Id == VarId);
            if (variant != null)
            {
                // Получаем данные перед удалением
                int numberBranch = variant.NumberBranch;
                string month = variant.PayCondition; // Предположим, что PayCondition содержит информацию о месяце или времени
                int year = DateTime.Now.Year; // Используем текущий год, если информация о годе отсутствует
                double revenue = 0; // Начальная сумма дохода, измените при необходимости для получения корректного значения

                // Удаляем вариант
                _context.PaymentConditions.Remove(variant);
                _context.SaveChanges();

                TempData["message"] = $"Вариант {variant.NumberBranch} удален.";

                // Обновляем другие данные
                UpdateCalculatedRevenue(numberBranch, month, year, revenue);
                UpdateProceeds();
                UpdatePaying();
                
                UpdatePaymentForecast();
                
            }
            else
            {
                TempData["message"] = $"Вариант не найден.";
            }
            return RedirectToAction(nameof(PaymentConditionInput));
        }


        public void UpdateCalculatedRevenue(int numberBranch, string month, int year, double revenue)
        {
            // Получаем текущие записи в таблице calculatedRevenueViewModels
            var existingRecords = _context.calculatedRevenueViewModels.ToList();

            // Получаем данные для обновления таблицы
            var paymentConditions = _context.PaymentConditions.AsEnumerable();
            var planRevenues = _context.PlanRevenues.AsEnumerable();

            var joinedPlan = (from paycon in paymentConditions
                              join reven in planRevenues on paycon.NumberBranch equals reven.NumberBranch
                              select new CalculatedRevenueViewModel
                              {
                                  NumberBranch = paycon.NumberBranch,
                                  Name = reven.Name,
                                  Month = reven.Month,
                                  Year = reven.Year,
                                  PaymentCondition = paycon.PayCondition,
                                  RevenueRes = paycon.Share * reven.Revenue
                              }).ToList();

            // Список для новых или обновленных записей
            var newOrUpdatedRecords = new List<CalculatedRevenueViewModel>();

            // Обновляем существующие записи или добавляем новые записи
            foreach (var item in joinedPlan)
            {
                var existingRecord = existingRecords.FirstOrDefault(r =>
                    r.NumberBranch == item.NumberBranch && r.Month == item.Month && r.Year == item.Year && r.PaymentCondition == item.PaymentCondition);

                if (existingRecord != null)
                {
                    // Обновляем существующую запись
                    existingRecord.RevenueRes = item.RevenueRes;
                    existingRecord.Name = item.Name; 
                    _context.Entry(existingRecord).State = EntityState.Modified;
                }
                else
                {
                    // Добавляем новую запись
                    newOrUpdatedRecords.Add(item);
                }
            }

            // Добавляем новые записи
            _context.calculatedRevenueViewModels.AddRange(newOrUpdatedRecords);

            // Удаляем старые записи, которых больше нет в новых данных
            var recordsToDelete = existingRecords
                .Where(r => !joinedPlan.Any(j =>

Payments/Payments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Payments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Payments.styles.css" asp-append-version="true" />
    <style>
        .nav-link.dropdown-toggle {
            color: #000000; /* Черный цвет */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Payments</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {                         
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" style="color: #000000;">Расчет коэффициентов</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index" >Исходные данные</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ImportFromExcelIndex" >Загрузка данных из excel-файла</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Result" >Расчет кол-ва дней до оплаты</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="CalculationCoeff" >Расчет долевых коэффициентов</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" style="color: #000000;">Прогноз из неоплаченных счетов</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="UnpaidInv" data-method="get">Данные о неоплаченных счетах</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ImportFromExcelUnpaidInv" data-method="get">Загрузка данных из excel-файла</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="UnpaidInvResult" data-method="post">Прогноз будущих платежей</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ForecastDateResult" data-method="get">Прогнозные даты платежей</a>
                                </div>

                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" style="color: #000000;">Прогноз из плановой выручки</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="PaymentConditionInput">Введение условия платежа</a>
                                    <div class="dropdown-submenu">
                                        <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="PlanRevenueInput">Планирование выручки</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="CalculatedRevenue" data-method="post">Расчет выручки</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="Proceeds" data-method="post">Выручка за месяц</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="Paying" data-method="get">Оплаты из плановой выручки</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="RevenueAndPayment" asp-action="PaymentForecast" data-method="get">Прогноз оплат из плановой выручки</a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" style="color: #000000;">Справочники</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="PayCondInput" data-method="get">Условия платежа</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="BranchInput">Филиалы</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="FinalForecast" >Итоговый прогноз</a>
                            </li>
                            <li class="nav-item separator"></li> <!-- Разделитель -->
                            <li class="nav-item">
                                <span class="nav-link text-black">@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-black" asp-area="" asp-controller="Login" asp-action="Logout">Выход</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-black" asp-area="" asp-controller="Login" asp-action="Index">Авторизация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

            2024-Пузыренко Е.М. Тема: Разработка программного обеспечения для прогнозирование поступления денежных средств от клиентов
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            $('.dropdown-item').on('click', function (e) {
                e.preventDefault();

                var action = $(this).attr('href');
                var method = $(this).data('method') || 'GET';

                var form = $('<form action="' + action + '" method="' + method + '"></form>');
                $('body').append(form);
                form.submit();
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>